### ISSUE TITLE
JuliaGraphs?

### ISSUE THREAD

**Issue by sbromberger** [EtymoIO/EvolvingGraphs.jl#2]
Would you consider putting this under the JuliaGraphs organization?

**Comment by weijianzhg** [comment]
Hi @sbromberger,

Thanks for the request. But EvolvingGraphs is more or less like an experimental thing for me. I don't know what it can be and where it goes, so I would like to keep it for myself for now.

Thanks,
Weijian

**Comment by sbromberger** [comment]
OK - just FYI, I borrowed some of your Katz Centrality for LightGraphs. Gave you credit (and included your license) in the source file. Please see https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/src/centrality/katz.jl and let me know if there's any issue. Thanks!

**Comment by weijianzhg** [comment]
No problem @sbromberger,  thanks for the credit.
