### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by weijianzhg** [EtymoIO/EvolvingGraphs.jl#3]
## Plan to Do
- Types
  - Use only two main types `IntAdjacencyList` and `IntIncidenceList` for evolving graphs.
  - Other types uses a dictionary to map input elements to an internal index.
  - two files for graph type: `evolving_graphs.jl` and `static_graphs.jl`
- Organization
  - move all the complex algorithms to a module `EvolvingGraphAlgs` and keep `EvolvingGraphs` 
    efficient and lightweight.

**Comment by sbromberger** [comment]
For plotting, you might check Iain's [GraphLayout](https://github.com/IainNZ/GraphLayout.jl).

**Comment by weijianzhg** [comment]
Thanks for the recommendation @sbromberger  :+1:  I will check it
