### ISSUE TITLE
Possible issue with katz_centrality

### ISSUE THREAD

**Issue by sbromberger** [EtymoIO/EvolvingGraphs.jl#5]
I ran into this one with LightGraphs (since I used your katz code there):

```
julia> g = evolving_graph(Int, String)
Directed EvolvingGraph (0 nodes, 0 edges, 0 timestamps)

julia> add_edge!(g,1,2,"t1"); add_edge!(g,2,3,"t1"); add_edge!(g,1,3,"t1"); add_edge!(g,3,4,"t1")
Directed EvolvingGraph (4 nodes, 4 edges, 1 timestamps)

julia> EvolvingGraphs.katz_centrality(g,0.4)
4-element Array{Tuple{Int64,Float64},1}:
 (4,0.3136745577315065)
 (3,0.4391443808241091)
 (2,0.4893323100611502)
 (1,0.6850652340856103)
```

but the same graph has a different Katz centrality in NetworkX:

```
In [11]: z = nx.katz_centrality(g,0.4)

In [12]: z
Out[12]:
{1: 0.3164769948422847,
 2: 0.44306779277919855,
 3: 0.620294909890878,
 4: 0.5645949587986359}
```

It appears that I can get LightGraphs (and presumably you could get Evolving Graphs) to yield the same results as NetworkX by transposing the adjacency matrix: `A = A'`. (That is, in LightGraphs, instead of using the outbound adjacency matrix, use the inbound.)

NetworkX is generally how I prove the correctness of my algorithms. It's entirely possible that they've got it wrong here, but my first instinct is to blame my own code :)

Would you mind helping me check this out?

Ref: [NetworkX](http://networkx.readthedocs.org/en/stable/reference/generated/networkx.algorithms.centrality.katz_centrality.html?highlight=katz#networkx.algorithms.centrality.katz_centrality)
Ref: https://github.com/JuliaGraphs/LightGraphs.jl/issues/151
cc: @jpfairbanks

**Comment by weijianzhg** [comment]
Hi @sbromberger ,

Thanks for the question. In Katz's original paper (http://people.cs.vt.edu/badityap/classes/cs6604-Fall13/readings/katz-1953.pdf), indeed, the transpose of the adjacency matrix `A` is used.  I think this is why NetworkX use the transpose of `A`. However, in many recent research papers, for example see (http://centaur.reading.ac.uk/19357/1/Coomunicability_accepted.pdf), both `A` and its transpose are considered.  
- the solution to the equation `(I - αA)x = ones(n)` is called broadcasting centrality which measures how effectively nodes can broadcast information; and
- the solution to the equation `(I - αA')x = ones(n)` is called receiving centrality.   

Actually, another implementation of `katz_centrality` in EvolvingGraphs gives both broadcasting and receiving centrality. See https://github.com/weijianzhang/EvolvingGraphs.jl/blob/master/src/algorithms/katz_centrality.jl#L44

Best wishes,

Weijian

**Comment by sbromberger** [comment]
Ah, cool - that makes sense and it's trivial to provide both types of centrality. Thank you very much for the explanation!

**Comment by sbromberger** [comment]
I've just added `mode=` to LightGraphs. Thanks again.

**Comment by weijianzhg** [comment]
You are welcome :)

**Comment by jpfairbanks** [comment]
@weijianzhang, there seems to be an inconsistency here [L19](https://github.com/weijianzhang/EvolvingGraphs.jl/blob/master/src/algorithms/katz_centrality.jl#L19) and [L59](https://github.com/weijianzhang/EvolvingGraphs.jl/blob/master/src/algorithms/katz_centrality.jl#L59)
One uses `v = S\v` and the other uses `v = S*ones`. Is the formula on line 59 computing the inverse of `S` or something?

**Comment by weijianzhg** [comment]
@jpfairbanks 

> Is the formula on line 59 computing the inverse of S or something?

Yes, you are right.
`S =  (spI + e^(-β*Δt)*S)*(spI + α*A) - spI` is an approximation of 
`S =  (spI + e^(-β*Δt)*S)*inv(spI - α*A) - spI`, 
where `inv(spI - α*A) = spI +  α*A +  α^2*A^2 +  α^3*A^3 + ...`

**Comment by jpfairbanks** [comment]
Is that close enough using only two terms of the analytic expansion?

I don't usually think of 1+x as close to 1/1-x

**Comment by weijianzhg** [comment]
@jpfairbanks well, I wouldn't say the approximation is very good. But in many cases, we want to just "restrict our attention to walks using at most one edge per time point".  This approximation was suggested by the original paper. "A Matrix Iteration for Dynamic Network Summaries", Peter Grindrod and Desmond J. Higham,  http://epubs.siam.org/doi/abs/10.1137/110855715
